services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  server:
    build:
      context: . # Sửa từ ./server thành .
      dockerfile: Dockerfile
    container_name: server
    restart: always
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://root:example@mongodb:27017
      - NODE_ENV=development
    depends_on:
      - mongodb

volumes:
  mongodb_data:
