name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.9.0"

      - name: Install dependencies - Server
        working-directory: ./server
        run: |
          yarn install

      - name: Build - Server
        working-directory: ./server
        run: yarn build

      - name: Test - Server
        working-directory: ./server
        run: |
          if [ -f "jest.config.js" ]; then
            yarn test
          else
            echo "No tests configured, skipping..."
          fi

      - name: Install dependencies - Client
        working-directory: ./client
        run: |
          yarn install

      - name: Build - Client
        working-directory: ./client
        run: yarn build
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        run: |
          # Build và push image cho backend
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest ./server
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest

          # Build và push image cho frontend
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/frontend:v1 ./client
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend:v1

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Deploy Backend to Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_BACKEND_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}

      - name: Deploy Frontend to Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_FRONTEND_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
